import {lazy,Suspense,useEffect,useState} from 'react';
import {Link,NavLink,Navigate,Outlet,Route,Routes,useLocation,useNavigate} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {AnimatePresence,motion} from 'framer-motion';
import {Bell,Camera,LogOut,Map,Menu,Settings,ShieldCheck,X} from 'lucide-react';
import {useAuth} from './auth';
import {eventStream} from './api';
import Landing,{Brand} from './Landing';
import AuthPage from './AuthPage';
import Monitor from './Monitor';
import LiveSession from './LiveSession';
import type {Source} from './types';
import Incidents from './Incidents';
import Alerts from './Alerts';
import SettingsPage from './SettingsPage';
import {Spinner} from './ui';
const MapPage=lazy(()=>import('./MapPage'));
function Workspace(){
 const {user,loading,logout}=useAuth();const location=useLocation();const navigate=useNavigate();const [notice,setNotice]=useState<string|null>(null);const query=useQueryClient();const [connected,setConnected]=useState(false);const [menu,setMenu]=useState(false);
 useEffect(()=>{if(!user)return;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|null=null;eventStream(controller.signal,event=>{if(event.kind==='frame'){query.setQueryData<Source[]>(['sources'],old=>old?.map(s=>s.id===event.data.id?{...s,tracks:event.data.tracks as Source['tracks'],fps:Number(event.data.fps),last_frame_at:String(event.data.last_frame_at)}:s));return;}if(event.kind==='incident'&&event.data.source_id)setNotice(String(event.data.source_id));if(timer)return;timer=setTimeout(()=>{['sources','jobs','incidents','stats','alerts','audit'].forEach(key=>query.invalidateQueries({queryKey:[key]}));timer=null;},150);},setConnected);return()=>{controller.abort();if(timer)clearTimeout(timer);};},[user,query]);
 useEffect(()=>setMenu(false),[location.pathname]);
 if(loading)return <div className="app-loading"><Spinner/>Opening your workspace</div>;if(!user)return <Navigate to="/login" state={{from:location.pathname}} replace/>;
 const nav=[{to:'/app',name:'Road monitoring',icon:Camera},{to:'/app/incidents',name:'Incident review',icon:ShieldCheck},{to:'/app/map',name:'Road network',icon:Map},{to:'/app/alerts',name:'Alert deliveries',icon:Bell},{to:'/app/settings',name:'Settings',icon:Settings}].filter(item=>user.role!=='visitor'||['/app','/app/incidents'].includes(item.to));
 return <div className="workspace"><header className="mobile-header"><Link to="/"><Brand/></Link><button className="icon-button" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header>{menu&&<div className="mobile-scrim" onClick={()=>setMenu(false)}/>}<aside className={'sidebar '+(menu?'sidebar-open':'')}><Link to="/" className="sidebar-brand"><Brand/></Link><div className="workspace-name"><div className="workspace-emblem"><Camera size={20}/></div><div><strong>{user.role==='visitor'?'Your private session':'Road operations'}</strong><span>{user.role==='visitor'?'Your camera & videos':'Monitoring workspace'}</span></div></div><span className="nav-label">WORKSPACE</span><nav>{nav.map(item=><NavLink to={item.to} end={item.to==='/app'} key={item.to}><item.icon size={19}/>{item.name}</NavLink>)}</nav><div className="sidebar-bottom"><div className={'connection '+(connected?'online':'')}><span/>{connected?'Live updates connected':'Reconnecting live updates'}<small>Accident Alert v1.0</small></div><div className="user-profile"><span className="avatar">{user.name.charAt(0).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.role}</small></div><button className="icon-button" onClick={()=>logout().then(()=>navigate('/')).catch(()=>{})} aria-label={user.role==='visitor'?'End private session':'Sign out'}><LogOut size={18}/></button></div></div></aside><main className="workspace-main"><div className="workspace-topbar"><span><Camera size={16}/>ROAD OPERATIONS</span><div><span className="topbar-date">{new Date().toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}</span><Link to="/app/incidents" className="icon-button" aria-label="Open incident review"><Bell size={19}/></Link></div></div><AnimatePresence>{notice&&<motion.div className="incident-notice" role="status" initial={{y:-20,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0}}><ShieldCheck size={20}/><Link to={'/app/live/'+notice} onClick={()=>setNotice(null)}>New candidate detected . Review evidence</Link><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice(null)}><X size={18}/></button></motion.div>}</AnimatePresence><AnimatePresence mode="wait"><motion.div className="page-content" key={location.pathname} initial={{opacity:0,y:9}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.2}}><Suspense fallback={<Spinner/>}><Outlet/></Suspense></motion.div></AnimatePresence><footer className="workspace-footer"><span>Accident Alert</span><span>Evidence first. Operator reviewed.</span></footer></main></div>;
}
export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/app" element={<Workspace/>}><Route index element={<Monitor/>}/><Route path="live/:identity" element={<LiveSession/>}/><Route path="incidents" element={<Incidents/>}/><Route path="map" element={<MapPage/>}/><Route path="alerts" element={<Alerts/>}/><Route path="settings" element={<SettingsPage/>}/></Route><Route path="*" element={<main className="not-found"><h1>This road ends here.</h1><p>The page could not be found.</p><Link className="button lime" to="/">Return home</Link></main>}/></Routes>;}
