import {useQuery} from '@tanstack/react-query';
import {motion,useReducedMotion} from 'framer-motion';
import {Camera,Video,Radio,BarChart3,Timer,ScanLine,ShieldCheck,Star,Quote,ArrowUpRight,Check} from 'lucide-react';
import {api} from './api';
import {ErrorMessage,Spinner} from './ui';
import StartFlow from './StartFlow';
import './landing-details.css';
type Testimonial={id:string;display_name:string;rating:number;quote:string;created_at:string};
export default function LandingDetails(){
 const reduced=useReducedMotion();const testimonials=useQuery({queryKey:['testimonials'],queryFn:()=>api<Testimonial[]>('/testimonials'),staleTime:60000});
 const reveal=reduced?{}:{initial:{opacity:0,y:30},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.55}};
 return <>
 <section className="landing-details" id="your-footage"><motion.div {...reveal} className="details-heading"><span className="eyebrow">03 / THREE WAYS TO SEE THE ROAD</span><h2>Your footage.<br/><span>Your point of view.</span></h2><p>Start with a recording. Bring a camera online when you’re ready. Every source has its own evidence, timeline, and analysis history.</p></motion.div><div className="input-cards">{[{icon:Video,title:'Recorded video',tag:'UPLOAD & EXPLORE',copy:'Upload road footage, watch analysis progress, and explore vehicle activity along the recording’s own timeline.',items:['Original playback and download','Saved graphs for each recording','Incident markers with review evidence']},{icon:Camera,title:'Your webcam',tag:'CAPTURE IN THE BROWSER',copy:'Choose your browser camera, start capture, and see actual frames and tracks arrive as they are processed.',items:['Start and stop capture yourself','Live vehicle and latency trends','Last 24 hours of analysis history']},{icon:Radio,title:'Connected CCTV',tag:'CONTINUOUS MONITORING',copy:'Connect an authorized camera stream through your operator workspace. Approve its host, then start monitoring.',items:['Server-side stream processing','Source health and latest frame','A shared incident review workflow']}].map((item,i)=><motion.article {...reveal} transition={{duration:.55,delay:reduced?0:i*.08}} key={item.title}><div className="input-card-icon"><item.icon size={28}/><ArrowUpRight size={17}/></div><span className="eyebrow">{item.tag}</span><h3>{item.title}</h3><p>{item.copy}</p><ul>{item.items.map(text=><li key={text}><Check size={14}/>{text}</li>)}</ul></motion.article>)}</div></section>
 <section className="landing-analytics" id="analysis"><motion.div {...reveal}><span className="eyebrow">04 / UNDERSTAND EACH SOURCE</span><h2>More than a frame.<br/><span>A measured timeline.</span></h2><p>Go from “what am I seeing?” to the exact moment that needs attention. Graphs are built from the frames your source actually processes.</p><div className="analysis-feature-list">{[{icon:BarChart3,title:'Vehicle activity over time',copy:'Compare average and peak vehicles per analyzed frame. Scrub the time inspector to see the measurements behind each interval.'},{icon:ScanLine,title:'A breakdown of vehicle types',copy:'See observed cars, motorcycles, buses, and trucks across analyzed frames, with clear totals and proportions.'},{icon:Timer,title:'Processing performance',copy:'Follow vision processing time alongside vehicle presence. Export the measured history as CSV.'},{icon:ShieldCheck,title:'Events with context',copy:'Open a candidate from its timeline and review the captured evidence. Follow its status from review through resolution.'}].map(item=><div key={item.title}><item.icon size={21}/><div><h3>{item.title}</h3><p>{item.copy}</p></div></div>)}</div></motion.div><motion.div {...reveal} className="analysis-flow-card"><div className="flow-orbit" aria-hidden="true"><div><ActivityIcon/></div><i/><i/></div><span className="eyebrow">ONE SOURCE. A COMPLETE VIEW.</span><h3>Capture → analyze → understand</h3><div className="pipeline-steps">{[['01','Your real footage','Video, webcam, or an approved camera stream'],['02','Measured observations','Vehicle tracks, motion signals, and processing time'],['03','Your analysis history','Time-based graphs and captured incident evidence']].map(([number,title,copy])=><div key={number}><span>{number}</span><div><strong>{title}</strong><small>{copy}</small></div></div>)}</div><p>Each recording keeps its own history. Live feeds retain the last 24 hours. Periods without analyzed frames remain gaps.</p></motion.div></section>
 <section className="landing-testimonials" id="feedback"><motion.div {...reveal} className="details-heading"><span className="eyebrow">05 / EXPERIENCES FROM THE WORKSPACE</span><h2>Real footage.<br/><span>Real feedback.</span></h2><p>Experiences shared after an analysis, published with the author’s permission.</p></motion.div><ErrorMessage error={testimonials.error}/>{testimonials.isPending?<div className="feedback-placeholder"><Spinner/>Loading community feedback</div>:testimonials.data?.length?<div className="testimonial-grid">{testimonials.data.map(t=><motion.article {...reveal} key={t.id}><Quote size={29}/><div className="review-stars" aria-label={`${t.rating} out of 5 stars`}>{[1,2,3,4,5].map(i=><Star key={i} size={15} fill={i<=t.rating?'currentColor':'none'}/>)}</div><blockquote>{t.quote}</blockquote><strong>{t.display_name}</strong><small>Shared after a footage analysis</small></motion.article>)}</div>:!testimonials.error&&<motion.div {...reveal} className="feedback-placeholder"><Quote size={34}/><div><h3>Be part of the first stories.</h3><p>No public reviews yet. Analyze your footage and share your experience from its analysis page. You choose whether your feedback may be published.</p></div><a href="#workspace" className="button outline">Explore your footage <ArrowUpRight size={16}/></a></motion.div>}</section>
 <section className="landing-faq"><motion.div {...reveal}><span className="eyebrow">06 / BEFORE YOU CONNECT</span><h2>A little clarity.<br/><span>Then get moving.</span></h2></motion.div><div>{[['Can I try it with my own video?','Yes. Sign in or register first, then choose Analyze a video, select your recording, and watch its processing progress. The source page shows the latest analyzed frame, saved charts, incident candidates, and original playback.'],['What does a vehicle count mean?','Vehicle presence counts tracked vehicles in each analyzed frame. Vehicle-type totals count observations across frames; the same vehicle can appear in several frames. They are not unique vehicle counts or calibrated traffic flow.'],['How do I connect a CCTV camera?','An operator can add a stream they own or have permission to use. The deployment administrator must approve the camera hostname before it can be connected. Start and stop the feed from its source page.'],['Are potential accidents automatically confirmed?','Potential incidents are motion-based candidates. An operator reviews the captured evidence and confirms or dismisses them. Optional AI summaries help explain the evidence; the motion score is not a crash probability.'],['Who can see my footage?','Videos, graphs and the dashboard require login or registration. All registered users can watch the shared recording collection. Your own uploads stay in your account. Team operators share their operations workspace. A public testimonial shows only the name, rating, and text you approved for publication.'],['Will the graphs still be there when I return?','Recording measurements are saved with that recording. Live-source graphs retain the last 24 hours. Older recordings without graph history can be analyzed again from the saved original.']].map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
 <section className="landing-final"><motion.div {...reveal}><span className="eyebrow">YOUR NEXT FRAME STARTS HERE</span><h2>Bring the road<br/><span>into focus.</span></h2><p>Connect real footage. Follow the movement. Review the evidence.</p><StartFlow compact/></motion.div></section>
 </>;
}
function ActivityIcon(){return <BarChart3 size={54}/>;}
