import {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Camera,Square,ArrowLeft,Video,Play,ShieldCheck,Clock,ScanLine,Activity,Download} from 'lucide-react';
import {api,raw,download} from './api';
import {EvidenceImage,ErrorMessage,Spinner,Status} from './ui';
import {IncidentDetail} from './Incidents';
import type {FrameResult,Incident,Job,Source} from './types';

export default function LiveSession(){
 const {identity}=useParams();const query=useQueryClient();const sources=useQuery({queryKey:['sources'],queryFn:()=>api<Source[]>('/sources'),refetchInterval:5000});const source=sources.data?.find(s=>s.id===identity);
 const incidents=useQuery({queryKey:['incidents'],queryFn:()=>api<Incident[]>('/incidents'),refetchInterval:5000});const jobs=useQuery({queryKey:['jobs'],queryFn:()=>api<Job[]>('/jobs'),refetchInterval:3000});const job=jobs.data?.find(j=>j.source_id===identity);
 const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const active=useRef(false);const controller=useRef<AbortController|null>(null);
 const [original,setOriginal]=useState('');const [loadingOriginal,setLoadingOriginal]=useState(false);
 const [running,setRunning]=useState(false);const [starting,setStarting]=useState(false);const [error,setError]=useState<unknown>();const [result,setResult]=useState<FrameResult|null>(null);const [frames,setFrames]=useState(0);const [latency,setLatency]=useState(0);const [rate,setRate]=useState(0);const [clock,setClock]=useState(Date.now());const [devices,setDevices]=useState<MediaDeviceInfo[]>([]);const [device,setDevice]=useState('');const [selected,setSelected]=useState<Incident|null>(null);
 const cleanup=useCallback(()=>{active.current=false;controller.current?.abort();stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;},[]);
 useEffect(()=>()=>{if(original)URL.revokeObjectURL(original);},[original]);
 async function reviewOriginal(){if(!job)return;setLoadingOriginal(true);try{const blob=await(await raw('/jobs/'+job.id+'/video')).blob();setOriginal(URL.createObjectURL(blob));}catch(e){setError(e);}finally{setLoadingOriginal(false);}}
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>()=>{cleanup();if(identity&&source?.kind==='webcam')api('/sources/'+identity+'/stop',{method:'POST'}).catch(()=>{});},[identity,cleanup,source?.kind]);
 async function stop(){cleanup();setRunning(false);try{await api('/sources/'+identity+'/stop',{method:'POST'});}catch(e){setError(e);}query.invalidateQueries({queryKey:['sources']});query.invalidateQueries({queryKey:['stats']});}
 async function capture(){
  const canvas=document.createElement('canvas');const context=canvas.getContext('2d')!;let previous=performance.now();
  while(active.current){
   const started=performance.now();try{
    const element=video.current;if(!element?.videoWidth){await new Promise(r=>setTimeout(r,100));continue;}
    const ratio=Math.min(1,960/element.videoWidth);canvas.width=Math.round(element.videoWidth*ratio);canvas.height=Math.round(element.videoHeight*ratio);context.drawImage(element,0,0,canvas.width,canvas.height);
    const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.78));if(!blob||!active.current)break;
    const body=new FormData();body.append('file',blob,'frame.jpg');const frame:FrameResult=await(await raw('/sources/'+identity+'/frame',{method:'POST',body,signal:controller.current?.signal})).json();
    if(!active.current)break;const now=performance.now();setResult(frame);setFrames(n=>n+1);setLatency(Math.round(now-started));setRate(Number((1000/(now-previous)).toFixed(1)));previous=now;
    query.setQueryData<Source[]>(['sources'],old=>old?.map(s=>s.id===identity?{...s,tracks:frame.tracks,fps:frame.processing_fps,last_frame_at:frame.processed_at,status:'live'}:s));
    if(frame.candidates)query.invalidateQueries({queryKey:['incidents']});
    await new Promise(r=>setTimeout(r,Math.max(0,500-(performance.now()-started))));
   }catch(e){if(active.current){setError(e);await stop();}break;}
  }
 }
 async function start(deviceId=device){
  setStarting(true);setError(undefined);
  try{
   if(!navigator.mediaDevices?.getUserMedia)throw new Error('Use HTTPS and a browser that supports camera access.');
   stream.current=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:960},height:{ideal:540},...(deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:'environment'}})},audio:false});
   if(!video.current)throw new Error('Camera preview is unavailable.');video.current.srcObject=stream.current;await video.current.play();
   await api('/sources/'+identity+'/start',{method:'POST'});setDevices((await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput'));setDevice(stream.current.getVideoTracks()[0].getSettings().deviceId||'');
   controller.current=new AbortController();active.current=true;setRunning(true);setFrames(0);setResult(null);capture();
  }catch(e){cleanup();setRunning(false);const name=(e as {name?:string}).name;setError(new Error(name==='NotAllowedError'?'Camera access was declined. Allow camera access in your browser, or analyze a video instead.':name==='NotFoundError'?'No camera found. Connect a camera or analyze a video instead.':e instanceof Error?e.message:'Camera could not start.'));}
  finally{setStarting(false);}
 }
 const ownIncidents=incidents.data?.filter(i=>i.source_id===identity)||[];const timestamp=result?.processed_at||source?.last_frame_at;const age=timestamp?Math.max(0,(clock-Date.parse(timestamp))/1000):null;const live=source?.kind==='webcam'?running&&age!==null&&age<5:source?.status==='live'&&age!==null&&age<10;const analyzing=source?.kind==='upload'&&['queued','processing'].includes(job?.status||'');
 if(sources.isPending)return <div className="loading-panel"><Spinner/>Opening your source</div>;
 if(!source)return <><ErrorMessage error={sources.error}/><h1>Source unavailable</h1><Link to="/app">Return to your sources</Link></>;
 return <><div className="live-heading"><div><Link to="/app" className="text-button"><ArrowLeft size={16}/>My sources</Link><h1>{source.name}</h1><Link className="text-button network-view-link" target="_blank" rel="noopener" title="Open the map while camera capture continues in this tab" to={'/app/map?source='+source.id}>{source.latitude===null?'Place footage on map':'View on road network'} <ArrowLeft size={14}/></Link></div><div className={'live-state '+(live?'active':'')}><i/>{live?'Receiving live frames':analyzing?'Analyzing uploaded video':job?.status==='completed'?'Analysis complete':job?.status==='failed'?'Analysis interrupted':job?.status==='cancelled'?'Analysis cancelled':starting?'Connecting camera':running?'Waiting for analysis':'Ready to start'}</div></div>
 <ErrorMessage error={error||jobs.error||source.last_error}/><div className="live-layout"><section className="live-stage"><div className="live-screen">
 {source.kind==='webcam'?<><video ref={video} autoPlay playsInline muted className={running?'camera-mini':'camera-hidden'}/>{result?<img src={result.image} alt="Actual camera frame with detected vehicle tracks"/>:<div className="live-ready"><Camera size={48}/><h2>{starting?'Connecting your camera':running?'Processing the first frame':'Your camera, live'}</h2>{starting||running?<Spinner/>:<button className="button lime" onClick={()=>start()}><Camera size={19}/>Enable camera & start</button>}</div>}</>:source.last_frame_at?<EvidenceImage path={'/sources/'+source.id+'/snapshot'} version={source.last_frame_at} alt={'Actual processed frame from '+source.name}/>:<div className="live-ready"><Video size={48}/><h2>{job?.status==='failed'?'Analysis failed':source.kind==='stream'?'Camera feed':'Preparing your video'}</h2>{analyzing?<Spinner/>:null}</div>}
 {timestamp&&<div className="frame-caption"><ScanLine size={15}/>{result?`Frame ${frames}`:'Latest analyzed frame'}<span>{age!<1?'Just received':`${Math.floor(age!)}s ago`}</span></div>}
 </div><div className="live-controls">{source.kind==='webcam'?<><button className={'button '+(running?'danger':'lime')} disabled={starting} onClick={()=>running?stop():start()}>{starting?<Spinner/>:running?<Square size={16}/>:<Camera size={18}/>} {running?'Stop camera':starting?'Connecting…':'Start camera'}</button>{devices.length>1&&<select aria-label="Camera device" value={device} onChange={async e=>{const id=e.target.value;setDevice(id);if(running){await stop();await start(id);}}}>{devices.map(d=><option value={d.deviceId} key={d.deviceId}>{d.label||'Camera'}</option>)}</select>}</>:source.kind==='stream'?<button className="button lime" onClick={async()=>{try{await api('/sources/'+identity+'/'+(source.status==='live'?'stop':'start'),{method:'POST'});query.invalidateQueries({queryKey:['sources']});query.invalidateQueries({queryKey:['stats']});}catch(e){setError(e);}}}>{source.status==='live'?<Square size={16}/>:<Play size={16}/>} {source.status==='live'?'Stop stream':'Start stream'}</button>:<><Status value={job?.status||'queued'}/>{analyzing&&<button className="button outline" onClick={stop}><Square size={16}/>Cancel analysis</button>}{['failed','cancelled'].includes(job?.status||'')&&<button className="button lime" onClick={async()=>{try{await api('/jobs/'+job!.id+'/retry',{method:'POST'});query.invalidateQueries({queryKey:['jobs']});query.invalidateQueries({queryKey:['sources']});}catch(e){setError(e);}}}><Play size={16}/>Retry analysis</button>}{job?.status==='completed'&&<button className="button outline" disabled={loadingOriginal} onClick={()=>{setError(undefined);if(original)setOriginal('');else reviewOriginal();}}>{loadingOriginal?<Spinner/>:<Play size={16}/>} {original?'Close playback':'Play original'}</button>}{job?.status==='completed'&&<button className="button outline" onClick={()=>download('/jobs/'+job.id+'/video',job.original_name).catch(setError)}><Download size={16}/>Original video</button>}</>}{source.kind==='webcam'&&<span className="muted">{running?'Keep this page open to continue capture':'Camera access is requested only when you start'}</span>}</div>
 {original&&<div className="original-playback"><video src={original} controls playsInline onError={()=>setError(new Error('Your browser cannot play this video format. Download the original video or use MP4 for browser playback.'))}/></div>}
 {job&&source.kind==='upload'&&<div className="analysis-progress"><progress value={job.progress} max={1}/><span><strong>{Math.round(job.progress*100)}%</strong> · {job.processed_frames} / {job.total_frames||'…'} frames decoded</span>{job.error&&<ErrorMessage error={job.error}/>}</div>}
 <div className="live-metrics"><div><ScanLine size={18}/><strong>{source.tracks.length}</strong><span>Vehicles in frame</span></div><div><Activity size={18}/><strong>{source.kind==='webcam'?(frames?rate:'—'):source.fps?source.fps:'—'}</strong><span>{source.kind==='webcam'?'Analyzed frames / sec':'Last inference frames / sec'}</span></div><div><Clock size={18}/><strong>{source.kind==='upload'?(job?.processed_frames??0):result?`${latency} ms`:'—'}</strong><span>{source.kind==='upload'?'Frames decoded':'Capture → result'}</span></div><div><ShieldCheck size={18}/><strong>{ownIncidents.filter(i=>i.status==='review').length}</strong><span>Needs review</span></div></div>
 </section><aside className="live-evidence"><div className="live-section-title"><h2>Vehicle tracks</h2><span>{source.tracks.length}</span></div>{source.tracks.length?<div className="track-list">{source.tracks.map(t=><div key={t.id}><span className="track-icon"><Video size={17}/></span><div><strong>{t.class}</strong><small>Track #{t.id}</small></div><span>{Math.round(t.confidence*100)}%<small>Detection confidence</small></span></div>)}</div>:<div className="live-zero"><ScanLine size={27}/><span>{timestamp?'No vehicles detected in this frame':'Tracks appear after a frame is analyzed'}</span></div>}<div className="live-section-title"><h2>Incident candidates</h2><span>{ownIncidents.length}</span></div>{ownIncidents.length?<div className="candidate-feed">{ownIncidents.map(i=><button key={i.id} onClick={()=>setSelected(i)}><EvidenceImage path={'/incidents/'+i.id+'/snapshot'} alt="Captured candidate frame"/><div><Status value={i.status}/><strong>{i.video_seconds!==null?`At ${i.video_seconds.toFixed(1)}s` : new Date(i.detected_at).toLocaleTimeString()}</strong><small>{i.signals.supporting_frames} supporting frames</small></div></button>)}</div>:<div className="live-zero"><ShieldCheck size={27}/><span>{timestamp?'No incident candidates detected':'Awaiting analyzed footage'}</span></div>}</aside></div>{selected&&<IncidentDetail incident={selected} onClose={()=>setSelected(null)}/>}</>;
}
