import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {MotionConfig} from 'framer-motion';
import {AuthProvider} from './auth';
import App from './App';
import './style.css';
import './blood-theme.css';
const query=new QueryClient({defaultOptions:{queries:{retry:1,staleTime:2000,refetchOnWindowFocus:true}}});
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={query}><BrowserRouter><MotionConfig reducedMotion="user"><AuthProvider><App/></AuthProvider></MotionConfig></BrowserRouter></QueryClientProvider></React.StrictMode>);
