import {useEffect,useRef} from 'react';
import {useQuery} from '@tanstack/react-query';
import L from 'leaflet';
import {MapPin} from 'lucide-react';
import {api} from './api';
import {ErrorMessage,Status} from './ui';
import type {Incident,Source} from './types';
import 'leaflet/dist/leaflet.css';
export default function MapPage(){
 const container=useRef<HTMLDivElement>(null);const map=useRef<L.Map|null>(null);const markers=useRef<L.LayerGroup|null>(null);const fitted=useRef(false);
 const sources=useQuery({queryKey:['sources'],queryFn:()=>api<Source[]>('/sources'),refetchInterval:10000});const incidents=useQuery({queryKey:['incidents'],queryFn:()=>api<Incident[]>('/incidents'),refetchInterval:10000});
 useEffect(()=>{if(!container.current)return;map.current=L.map(container.current,{zoomControl:true}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map.current);markers.current=L.layerGroup().addTo(map.current);const observer=new ResizeObserver(()=>map.current?.invalidateSize());observer.observe(container.current);return()=>{observer.disconnect();map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!markers.current||!map.current)return;markers.current.clearLayers();const points:L.LatLngExpression[]=[];for(const source of sources.data||[]){if(source.latitude===null||source.longitude===null)continue;const point:L.LatLngExpression=[source.latitude,source.longitude];points.push(point);const content=document.createElement('div');const title=document.createElement('strong');title.textContent=source.name;const detail=document.createElement('p');detail.textContent=source.location;content.append(title,detail);L.circleMarker(point,{radius:8,color:'#b4f35c',weight:2,fillColor:'#172b13',fillOpacity:.9}).bindPopup(content).addTo(markers.current);}for(const incident of incidents.data||[]){if(incident.latitude===null||incident.longitude===null)continue;const point:L.LatLngExpression=[incident.latitude,incident.longitude];points.push(point);const content=document.createElement('div');const title=document.createElement('strong');title.textContent=incident.source_name;const detail=document.createElement('p');detail.textContent=incident.status+' · '+new Date(incident.detected_at).toLocaleString();content.append(title,detail);L.circleMarker(point,{radius:14,color:incident.status==='review'?'#ffbb6b':incident.status==='confirmed'?'#ff6b6b':'#83939c',fillOpacity:.2,weight:2}).bindPopup(content).addTo(markers.current);}if(points.length&&!fitted.current){map.current.fitBounds(L.latLngBounds(points),{padding:[50,50],maxZoom:15});fitted.current=true;}},[sources.data,incidents.data]);
 const located=sources.data?.filter(s=>s.latitude!==null&&s.longitude!==null)||[];
 return <><div className="page-title"><div><span className="eyebrow">COVERAGE / INCIDENT LOCATIONS</span><h1>Your road network<span className="title-dot">.</span></h1><p>Source locations and recorded incidents, placed using your camera coordinates.</p></div></div><ErrorMessage error={sources.error||incidents.error}/><div className="map-layout"><div className="map-container" ref={container} role="region" aria-label="Map of configured sources and incident locations"/><aside className="map-aside"><h2>Source locations</h2><p className="muted">{located.length} source{located.length===1?'':'s'} with coordinates</p>{located.length?located.map(source=><button className="map-source" key={source.id} onClick={()=>map.current?.setView([source.latitude!,source.longitude!],15)}><MapPin size={17}/><span><strong>{source.name}</strong><small>{source.location}</small><Status value={source.status}/></span></button>):<p className="map-empty">Add latitude and longitude when connecting a source to display it on this map.</p>}<div className="map-legend"><span><i className="lime-dot"/>Camera source</span><span><i className="amber-dot"/>Needs review</span><span><i className="red-dot"/>Confirmed incident</span></div></aside></div></>;
}
