import {useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Camera,CameraOff,FileVideo,MapPin,Plus,Radio,ScanLine,Square,Upload,Archive} from 'lucide-react';
import {api,raw} from './api';
import {useAuth} from './auth';
import {EvidenceImage,Empty,ErrorMessage,Spinner,Status,date} from './ui';
import SourceForm from './SourceForm';
import Webcam from './Webcam';
import type {Job,Source,Stats} from './types';
export default function Monitor(){
 const sources=useQuery({queryKey:['sources'],queryFn:()=>api<Source[]>('/sources'),refetchInterval:5000});const stats=useQuery({queryKey:['stats'],queryFn:()=>api<Stats>('/stats'),refetchInterval:10000});const jobs=useQuery({queryKey:['jobs'],queryFn:()=>api<Job[]>('/jobs'),refetchInterval:5000});const query=useQueryClient();const {user}=useAuth();const [add,setAdd]=useState(false);const [webcam,setWebcam]=useState<Source|null>(null);const [error,setError]=useState<unknown>();const [busy,setBusy]=useState('');const file=useRef<HTMLInputElement>(null);const selected=useRef<Source|null>(null);
 async function action(source:Source,what:string){setBusy(source.id);setError(undefined);try{await api('/sources/'+source.id+'/'+what,{method:'POST'});query.invalidateQueries({queryKey:['sources']});}catch(e){setError(e);}finally{setBusy('');}}
 function choose(source:Source){selected.current=source;file.current?.click();}
 async function upload(video:File){const source=selected.current;if(!source)return;setBusy(source.id);setError(undefined);try{const body=new FormData();body.append('file',video);await raw('/sources/'+source.id+'/upload',{method:'POST',body});query.invalidateQueries({queryKey:['jobs']});}catch(e){setError(e);}finally{setBusy('');if(file.current)file.current.value='';}}
 const values=stats.data;
 return <><div className="page-title"><div><span className="eyebrow">OPERATIONS / LIVE OVERVIEW</span><h1>Road monitoring<span className="title-dot">.</span></h1><p>Your sources, their latest frames, and the evidence that needs attention.</p></div><button className="button lime" onClick={()=>setAdd(true)}><Plus size={19}/>Connect source</button></div><ErrorMessage error={error||sources.error||stats.error||jobs.error}/>
 <div className="stats-grid">{[{label:'Connected sources',value:values?.sources,icon:Camera},{label:'Live cameras',value:values?.live,icon:Radio},{label:'Awaiting review',value:values?.review,icon:ScanLine},{label:'Delivered alerts',value:values?.delivered,icon:FileVideo}].map(item=><div className="stat-card" key={item.label}><span>{item.label}<item.icon size={18}/></span><strong>{item.value??'—'}</strong></div>)}</div>
 <div className="section-row"><h2>Connected sources <span>{sources.data?.length??0}</span></h2><span className="muted">Latest processed frames</span></div>
 {sources.isPending?<div className="loading-panel"><Spinner/>Connecting to your workspace</div>:!sources.data?.length?<Empty icon={<CameraOff size={30}/>} title="Your road network starts here" text="Connect a camera or upload a video to begin monitoring. Detected candidates will appear in your incident review queue." action={<button className="button outline" onClick={()=>setAdd(true)}><Plus size={18}/>Connect your first source</button>}/>:<div className="sources-grid">{sources.data.map(source=><article className="source-card" key={source.id}><div className="source-view">{source.last_frame_at?<EvidenceImage path={'/sources/'+source.id+'/snapshot'} version={source.last_frame_at} alt={'Latest processed frame from '+source.name}/>:<div className="source-placeholder"><ScanLine size={34}/><span>{source.kind==='upload'?'Upload footage to begin':'Waiting for camera frames'}</span></div>}<div className="source-overlay"><span>{source.kind==='stream'?'CCTV':source.kind==='webcam'?'WEBCAM':'VIDEO'}</span><Status value={source.status==='live'&&(!source.last_frame_at||Date.now()-Date.parse(source.last_frame_at)>30000)?'idle':source.status}/></div></div><div className="source-content"><h3>{source.name}</h3><p><MapPin size={14}/>{source.location}</p><div className="source-data"><span>{source.tracks.length} tracked vehicles</span><span>{source.last_frame_at?date(source.last_frame_at):'No frames yet'}</span></div>{source.last_error&&<div className="source-error">{source.last_error}</div>}<div className="source-actions">{source.kind==='upload'?<button className="button outline" onClick={()=>choose(source)} disabled={busy===source.id||source.status==='processing'}>{busy===source.id?<Spinner/>:<Upload size={16}/>}Upload video</button>:source.kind==='webcam'?<button className="button outline" onClick={()=>setWebcam(source)}><Camera size={16}/>Open webcam</button>:<button className="button outline" onClick={()=>action(source,source.status==='live'?'stop':'start')} disabled={busy===source.id}>{busy===source.id?<Spinner/>:source.status==='live'?<Square size={15}/>:<Radio size={16}/>} {source.status==='live'?'Stop monitoring':'Start monitoring'}</button>}{user?.role==='admin'&&<button className="icon-button" aria-label={'Archive '+source.name} title="Archive source" onClick={()=>action(source,'archive')} disabled={busy===source.id}><Archive size={17}/></button>}</div></div></article>)}</div>}
 <div className="section-row"><h2>Video processing</h2><span className="muted">Uploads run in the background</span></div>{!jobs.data?.length?<div className="quiet-panel"><FileVideo size={20}/>Upload a road video to an uploaded-video source to start analysis.</div>:<div className="jobs-panel">{jobs.data.map(job=><div className="job-row" key={job.id}><FileVideo size={23}/><div className="job-info"><strong>{job.original_name}</strong><span>{job.source_name} · {date(job.created_at)}</span>{job.error&&<small className="source-error">{job.error}</small>}</div><div className="job-progress"><div><i style={{width:Math.round(job.progress*100)+'%'}}/></div><small>{Math.round(job.progress*100)}% · {job.processed_frames} / {job.total_frames||'—'} frames</small></div><Status value={job.status}/>{['processing','queued'].includes(job.status)&&<button className="icon-button" aria-label="Cancel processing" onClick={()=>action({id:job.source_id} as Source,'stop')}><Square size={16}/></button>}</div>)}</div>}
 <input ref={file} type="file" accept="video/mp4,video/webm,video/quicktime,.avi,.mkv" hidden onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);}}/>
 {add&&<SourceForm onClose={()=>setAdd(false)} onCreated={source=>{if(source.kind==='webcam')setWebcam(source);if(source.kind==='upload')setTimeout(()=>choose(source),100);}}/>}{webcam&&<Webcam source={webcam} onClose={()=>setWebcam(null)}/>}</>;
}
