import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import L from 'leaflet';
import {ArrowUpRight,Camera,Check,LocateFixed,MapPin,Search,ShieldCheck,X} from 'lucide-react';
import {api} from './api';
import {EvidenceImage,ErrorMessage,Spinner,Status} from './ui';
import {IncidentDetail} from './Incidents';
import StartFlow from './StartFlow';
import type {Incident,Source} from './types';
import 'leaflet/dist/leaflet.css';

type Placement={id:string;location:string;latitude:string;longitude:string};
function health(s:Source,now:number){if(s.status==='error'||s.status==='processing')return s.status;if(s.status==='live')return s.last_frame_at&&now-Date.parse(s.last_frame_at)<10000?'live':'delayed';return 'idle';}
function frameAge(value:string|null,now:number){if(!value)return 'No frames received';const seconds=Math.max(0,Math.floor((now-Date.parse(value))/1000));return seconds<2?'Frame just received':seconds<60?`Last frame ${seconds}s ago`:seconds<3600?`Last frame ${Math.floor(seconds/60)}m ago`:`Last frame ${Math.floor(seconds/3600)}h ago`;}
const colors:Record<string,string>={live:'#ff4057',delayed:'#e6a7b6',error:'#ff6d7a',processing:'#f35578',idle:'#907c82'};

export default function RoadNetwork(){
 const container=useRef<HTMLDivElement>(null);const map=useRef<L.Map|null>(null);const sourceMarkers=useRef(new Map<string,L.CircleMarker>());const incidentMarkers=useRef(new Map<string,L.CircleMarker>());const draftMarker=useRef<L.Marker|null>(null);const fitted=useRef(false);
 const [params]=useSearchParams();const [selectedId,setSelectedId]=useState(params.get('source')||'');const [placement,setPlacement]=useState<Placement|null>(null);const [review,setReview]=useState<Incident|null>(null);const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [now,setNow]=useState(Date.now());const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();
 const query=useQueryClient();const sources=useQuery({queryKey:['sources'],queryFn:()=>api<Source[]>('/sources'),refetchInterval:5000});const incidents=useQuery({queryKey:['incidents','network'],queryFn:()=>api<Incident[]>('/incidents?active_only=true&limit=500'),refetchInterval:5000});
 const all=sources.data||[];const active=(incidents.data||[]).filter(i=>['review','confirmed'].includes(i.status));const located=all.filter(s=>s.latitude!==null&&s.longitude!==null);const unlocated=all.filter(s=>s.latitude===null||s.longitude===null);const selected=all.find(s=>s.id===selectedId&&(s.name+' '+s.location).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='live'&&health(s,now)==='live'||filter==='review'&&active.some(i=>i.source_id===s.id))); const selectedIncidents=active.filter(i=>i.source_id===selectedId);
 const visible=all.filter(s=>(s.name+' '+s.location).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='live'&&health(s,now)==='live'||filter==='review'&&active.some(i=>i.source_id===s.id)));
 const clickMap=useRef<(point:L.LatLng)=>void>(()=>{});clickMap.current=point=>setPlacement(old=>old?{...old,latitude:point.lat.toFixed(6),longitude:point.lng.toFixed(6)}:null);
 const selectSource=useRef<(id:string)=>void>(()=>{});selectSource.current=id=>{setSelectedId(id);const s=all.find(s=>s.id===id);if(s?.latitude!==null&&s?.latitude!==undefined&&s.longitude!==null)map.current?.flyTo([s.latitude,s.longitude],16,{animate:!window.matchMedia('(prefers-reduced-motion:reduce)').matches,duration:.6});};
 const openIncident=useRef<(sourceId:string)=>void>(()=>{});openIncident.current=id=>{const incident=active.find(i=>i.source_id===id);if(incident)setReview(incident);};
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!selectedId&&all.length)setSelectedId(all[0].id);},[sources.data,selectedId]);
 useEffect(()=>{
  if(!container.current)return;const instance=L.map(container.current,{zoomControl:true}).setView([20,0],2);map.current=instance;
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(instance);
  instance.on('click',event=>clickMap.current(event.latlng));const observer=new ResizeObserver(()=>instance.invalidateSize());observer.observe(container.current);
  return()=>{observer.disconnect();instance.remove();map.current=null;sourceMarkers.current.clear();incidentMarkers.current.clear();};
 },[]);
 useEffect(()=>{
  const instance=map.current;if(!instance)return;const wanted=new Set<string>();
  for(const source of visible){if(source.latitude===null||source.longitude===null)continue;wanted.add(source.id);let marker=sourceMarkers.current.get(source.id);
   if(!marker){marker=L.circleMarker([source.latitude,source.longitude],{bubblingMouseEvents:false,fillOpacity:.9,weight:3}).addTo(instance);marker.on('click',()=>selectSource.current(source.id));sourceMarkers.current.set(source.id,marker);}
   marker.setLatLng([source.latitude,source.longitude]);marker.setStyle({color:colors[health(source,now)],fillColor:health(source,now)==='live'?'#380a14':'#10070b',radius:selectedId===source.id?12:8});
   const text=document.createElement('span');text.textContent=source.name+' · '+health(source,now)+' · '+frameAge(source.last_frame_at,now);marker.unbindTooltip().bindTooltip(text);
  }
  for(const [id,marker] of sourceMarkers.current)if(!wanted.has(id)){marker.remove();sourceMarkers.current.delete(id);}
  const incidentIds=new Set<string>();
  for(const incident of active){if(incident.latitude===null||incident.longitude===null||filter==='live'||search&&!((incident.source_name+' '+incident.location).toLowerCase().includes(search.toLowerCase())))continue;
   // One ring per source keeps incidents at the same camera location readable.
   if(incidentIds.has(incident.source_id))continue;incidentIds.add(incident.source_id);let marker=incidentMarkers.current.get(incident.source_id);
   if(!marker){marker=L.circleMarker([incident.latitude,incident.longitude],{radius:23,bubblingMouseEvents:false,weight:2,fillOpacity:.15}).addTo(instance);marker.on('click',()=>openIncident.current(incident.source_id));incidentMarkers.current.set(incident.source_id,marker);}
   const group=active.filter(i=>i.source_id===incident.source_id);marker.setLatLng([incident.latitude,incident.longitude]);marker.setStyle({color:group.some(i=>i.status==='confirmed')?'#ff6d7a':'#e6a7b6'});const text=document.createElement('span');text.textContent=`${group.length} active incident${group.length===1?'':'s'} · Click to review`;marker.unbindTooltip().bindTooltip(text);marker.bringToBack();
  }
  for(const [id,marker] of incidentMarkers.current)if(!incidentIds.has(id)){marker.remove();incidentMarkers.current.delete(id);}
  if(located.length&&!fitted.current){instance.fitBounds(L.latLngBounds(located.map(s=>[s.latitude!,s.longitude!])),{padding:[45,45],maxZoom:15});fitted.current=true;}
 },[sources.data,incidents.data,now,selectedId,search,filter]);
 useEffect(()=>{
  draftMarker.current?.remove();draftMarker.current=null;const instance=map.current;if(!placement||!instance)return;
  if(placement.latitude!==''&&placement.longitude!==''&&Number.isFinite(Number(placement.latitude))&&Number.isFinite(Number(placement.longitude))&&Math.abs(Number(placement.latitude))<=90&&Math.abs(Number(placement.longitude))<=180){const marker=L.marker([Number(placement.latitude),Number(placement.longitude)],{draggable:true,icon:L.divIcon({className:'placement-pin',html:'+',iconSize:[32,32],iconAnchor:[16,16]})}).addTo(instance);marker.on('dragend',()=>clickMap.current(marker.getLatLng()));draftMarker.current=marker;}
  container.current?.classList.toggle('placing-source',!!placement);return()=>{container.current?.classList.remove('placing-source');};
 },[placement]);
 function place(source:Source){setError(undefined);setSelectedId(source.id);setPlacement({id:source.id,location:source.location==='Location not provided'?'':source.location,latitude:source.latitude===null?'':String(source.latitude),longitude:source.longitude===null?'':String(source.longitude)});}
 async function saveLocation(event:FormEvent){event.preventDefault();if(!placement)return;setBusy(true);setError(undefined);try{const source=await api<Source>('/sources/'+placement.id+'/location',{method:'PATCH',body:JSON.stringify({location:placement.location,latitude:Number(placement.latitude),longitude:Number(placement.longitude)})});query.setQueryData<Source[]>(['sources'],old=>old?.map(s=>s.id===source.id?source:s));query.invalidateQueries({queryKey:['incidents']});setPlacement(null);map.current?.flyTo([source.latitude!,source.longitude!],16,{animate:!window.matchMedia('(prefers-reduced-motion:reduce)').matches});}catch(e){setError(e);}finally{setBusy(false);}}
 function fit(){if(located.length)map.current?.fitBounds(L.latLngBounds(located.map(s=>[s.latitude!,s.longitude!])),{padding:[45,45],maxZoom:16});}
 function nearby(){setError(undefined);if(!navigator.geolocation){setError(new Error('Your browser cannot locate this device. Zoom the map or enter coordinates.'));return;}navigator.geolocation.getCurrentPosition(position=>map.current?.setView([position.coords.latitude,position.coords.longitude],15),()=>setError(new Error('Device location is unavailable. You can zoom the map or enter coordinates manually.')),{timeout:15000,maximumAge:60000});}
 const fresh=all.filter(s=>health(s,now)==='live').length;
 return <><div className="page-title"><div><span className="eyebrow">NETWORK / LIVE OPERATIONS</span><h1>Road network<span className="title-dot">.</span></h1></div><div className="network-toolbar"><button className="button outline" onClick={nearby}><MapPin size={17}/>Go to my area</button><button className="button outline" onClick={fit} disabled={!located.length}><LocateFixed size={17}/>Fit coverage</button></div></div><ErrorMessage error={error||sources.error||incidents.error}/>
  <div className="network-summary"><span><i className={fresh?'lime-dot':'network-idle-dot'}/><strong>{fresh}</strong> live cameras</span><span><MapPin size={16}/><strong>{located.length}</strong> mapped sources</span><span><ShieldCheck size={16}/><strong>{active.length}{active.length===500?'+':''}</strong> active incidents</span><span className="network-sync">{sources.data?`Sources synced ${Math.max(0,Math.floor((now-sources.dataUpdatedAt)/1000))}s ago`:'Connecting…'}</span></div>
  {!all.length&&!sources.isPending&&<div className="network-start"><Camera size={24}/><div><strong>Connect footage to see your coverage.</strong><StartFlow/></div></div>}
  <div className="network-layout"><section className="network-map-stage"><div className="map-container network-map" ref={container} role="region" aria-label="Live source coverage and incident map"/>{placement&&<div className="map-placement-hint"><MapPin size={17}/>Click the map where this footage was captured.</div>}<div className="network-map-legend"><span><i className="lime-dot"/>Receiving frames</span><span><i className="network-idle-dot"/>Idle</span><span><i className="amber-dot"/>Review / delayed</span><span><i className="red-dot"/>Confirmed / error</span></div></section>
  <aside className="network-panel">{placement?<form className="network-placement" onSubmit={saveLocation}><div className="network-panel-heading"><h2>Place {all.find(s=>s.id===placement.id)?.name}</h2><button type="button" className="icon-button" aria-label="Cancel placement" disabled={busy} onClick={()=>setPlacement(null)}><X size={18}/></button></div><label>Road or area<input required minLength={2} maxLength={200} value={placement.location} onChange={e=>setPlacement({...placement,location:e.target.value})} placeholder="Where was this footage captured?"/></label><div className="form-row"><label>Latitude<input required type="number" step="any" min={-90} max={90} value={placement.latitude} onChange={e=>setPlacement({...placement,latitude:e.target.value})}/></label><label>Longitude<input required type="number" step="any" min={-180} max={180} value={placement.longitude} onChange={e=>setPlacement({...placement,longitude:e.target.value})}/></label></div><button className="button lime full" disabled={busy}>{busy?<Spinner/>:<Check size={17}/>}Save location</button></form>:<>
   <label className="search network-search"><Search size={16}/><input aria-label="Find a source or road" placeholder="Find a source or road" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="network-filters">{[['all','All sources'],['live','Live'],['review','Incidents']].map(([value,label])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{label}</button>)}</div>
   {filter==='review'&&<div className="network-queue"><div className="network-panel-heading"><h2>Incident queue</h2><Link className="text-button" to="/app/incidents">View all</Link></div>{active.filter(i=>(i.source_name+' '+i.location).toLowerCase().includes(search.toLowerCase())).slice(0,20).map(incident=><button className="network-incident" key={incident.id} onClick={()=>setReview(incident)}><EvidenceImage path={'/incidents/'+incident.id+'/snapshot'} alt="Captured incident evidence"/><span><strong>{incident.source_name}</strong><Status value={incident.status}/><small>{incident.latitude===null?'Location not assigned':incident.location}</small></span><ArrowUpRight size={16}/></button>)}{!active.length&&<p className="network-empty">No active incidents.</p>}</div>}
   <div className="network-source-list">{sources.isPending?<Spinner/>:visible.length?visible.map(source=><button className={'network-source '+(selectedId===source.id?'selected':'')} key={source.id} onClick={()=>selectSource.current(source.id)}><i style={{background:colors[health(source,now)]}}/><span><strong>{source.name}</strong><small>{source.latitude===null?'Not placed on map':source.location}</small></span><small>{health(source,now)}</small></button>):<p className="network-empty">{all.length?'No sources match this filter.':'No sources connected yet.'}</p>}</div>
   {selected&&<section className="network-detail"><div className="network-panel-heading"><h2>{selected.name}</h2><Status value={health(selected,now)}/></div>{selected.last_frame_at?<EvidenceImage path={'/sources/'+selected.id+'/snapshot'} version={selected.last_frame_at} alt={'Latest actual frame from '+selected.name}/>:<div className="network-no-frame"><Camera size={24}/>{selected.kind==='upload'?'No video analyzed yet':'Waiting for camera frames'}</div>}<div className="network-frame-info"><span>{frameAge(selected.last_frame_at,now)}</span><span>{selected.tracks.length} vehicles in frame</span></div><div className="network-detail-actions"><Link className="button lime small" target="_blank" rel="noopener" title="Keep the map open while viewing or capturing footage" to={'/app/live/'+selected.id}>Open live view <ArrowUpRight size={16}/></Link><button className="button outline small" onClick={()=>place(selected)}><MapPin size={16}/>{selected.latitude===null?'Place on map':'Edit location'}</button></div>{selected.last_error&&<ErrorMessage error={selected.last_error}/>}<div className="network-panel-heading"><h2>Active incidents</h2><span>{selectedIncidents.length}</span></div>{selectedIncidents.length?selectedIncidents.map(incident=><button className="network-incident" key={incident.id} onClick={()=>setReview(incident)}><EvidenceImage path={'/incidents/'+incident.id+'/snapshot'} alt="Captured incident evidence"/><span><Status value={incident.status}/><small>{new Date(incident.detected_at).toLocaleTimeString()}</small></span><ArrowUpRight size={16}/></button>):<p className="network-empty">No active incidents for this source.</p>}</section>}
  </>}</aside></div>{unlocated.length>0&&<div className="network-unmapped"><MapPin size={19}/><span><strong>{unlocated.length} source{unlocated.length===1?'':'s'} without a map location</strong>Select a source and place it where the footage was captured.</span><button className="button outline small" onClick={()=>place(unlocated[0])}>Place a source</button></div>}{review&&<IncidentDetail incident={incidents.data?.find(i=>i.id===review.id)||review} onClose={()=>setReview(null)}/>}</>;
}
