import {useState,type FormEvent} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {Camera,MapPin,Radio,Upload} from 'lucide-react';
import {api} from './api';
import {useAuth} from './auth';
import {ErrorMessage,Modal,Spinner} from './ui';
import type {Source} from './types';
export default function SourceForm({onClose,onCreated}:{onClose:()=>void;onCreated:(source:Source)=>void}){
 const {user}=useAuth();const [kind,setKind]=useState<Source['kind']>('upload');const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const [coords,setCoords]=useState({latitude:'',longitude:''});const query=useQueryClient();
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError(undefined);const data=Object.fromEntries(new FormData(event.currentTarget));try{const source=await api<Source>('/sources',{method:'POST',body:JSON.stringify({...data,kind,latitude:coords.latitude?Number(coords.latitude):null,longitude:coords.longitude?Number(coords.longitude):null})});query.invalidateQueries({queryKey:['sources']});onCreated(source);onClose();}catch(e){setError(e);}finally{setBusy(false);}}
 function locate(){if(!navigator.geolocation){setError(new Error('Location is unavailable in this browser'));return;}navigator.geolocation.getCurrentPosition(position=>setCoords({latitude:String(position.coords.latitude),longitude:String(position.coords.longitude)}),()=>setError(new Error('Location permission was declined. You can enter coordinates manually.')));}
 return <Modal title="Connect a source" onClose={onClose}><p className="muted">Choose where your footage comes from and where the camera is located.</p><div className="source-types">{[{value:'upload',icon:Upload,name:'Video upload'},{value:'webcam',icon:Camera,name:'Webcam'},...(user?.role==='admin'?[{value:'stream',icon:Radio,name:'CCTV stream'}]:[])].map(item=><button type="button" key={item.value} className={kind===item.value?'selected':''} onClick={()=>setKind(item.value as Source['kind'])}><item.icon size={23}/>{item.name}</button>)}</div><ErrorMessage error={error}/><form onSubmit={submit}><label>Source name<input name="name" placeholder="Give this source a name" required minLength={2} maxLength={100}/></label><label>Road or location<input name="location" placeholder="Road name, junction, or area" required minLength={2} maxLength={200}/></label>{kind==='stream'&&<label>Camera stream URL<input name="stream_url" type="url" placeholder="rtsp://camera-host/stream" required/><small>Its hostname must be approved in your server's camera allowlist. RTSP, RTSPS, HTTP, and HTTPS are supported.</small></label>}<div className="form-row"><label>Latitude <span className="optional">optional</span><input type="number" step="any" min={-90} max={90} value={coords.latitude} onChange={e=>setCoords({...coords,latitude:e.target.value})}/></label><label>Longitude <span className="optional">optional</span><input type="number" step="any" min={-180} max={180} value={coords.longitude} onChange={e=>setCoords({...coords,longitude:e.target.value})}/></label></div><button className="text-button" type="button" onClick={locate}><MapPin size={15}/> Use my current location</button><button className="button lime full" disabled={busy}>{busy?<Spinner/>:null}Connect source</button></form></Modal>;
}
