import {useState,type FormEvent} from 'react';
import {useInfiniteQuery,useQuery,useQueryClient} from '@tanstack/react-query';
import {Activity,BarChart3,Clock,Download,MessageSquare,Play,ShieldCheck,Star} from 'lucide-react';
import {api} from './api';
import {useAuth} from './auth';
import {ErrorMessage,Spinner,Status} from './ui';
import type {Incident,Job,Source} from './types';
import './analytics.css';

type Point={at:string;end_at:string;video_seconds:number|null;video_end_seconds:number|null;samples:number;vehicles:number;peak:number;vision_ms:number};
type Analytics={job_id:string|null;window_minutes:number;retention_hours:number;bucket_seconds:number;
 summary:{samples:number;peak:number;average_vehicles:number;average_vision_ms:number;cars:number;motorcycles:number;buses:number;trucks:number;first_at:string|null;last_at:string|null;first_video_seconds:number|null;last_video_seconds:number|null};
 points:Point[];events:Incident[];events_truncated:boolean;recording:{id:string;original_name:string;status:string}|null};
const n=(value:number)=>Number(value).toLocaleString(undefined,{maximumFractionDigits:1});
const elapsed=(value:number)=>`${Math.floor(value/60)}:${String(Math.floor(value%60)).padStart(2,'0')}`;
function time(point:Point,recorded:boolean){return recorded?elapsed(point.video_seconds||0):new Date(point.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function stamp(point:Point,recorded:boolean){return recorded?point.video_seconds||0:Date.parse(point.at)/1000;}

function Trend({points,recorded,bucketSeconds,metric,title,unit,onSelect,index}:{points:Point[];recorded:boolean;bucketSeconds:number;metric:'vehicles'|'vision_ms';title:string;unit:string;onSelect:(i:number)=>void;index:number}){
 const width=640,height=174,left=42,right=20,top=18,bottom=30;
 const values=points.flatMap(p=>metric==='vehicles'?[Number(p.vehicles),Number(p.peak)]:[Number(p.vision_ms)]);
 const max=Math.max(1,...values)*1.12;const start=stamp(points[0],recorded),end=stamp(points.at(-1)!,recorded);const span=Math.max(bucketSeconds,end-start);
 const x=(p:Point)=>left+(stamp(p,recorded)-start)/span*(width-left-right);
 const y=(v:number)=>height-bottom-v/max*(height-top-bottom);
 function path(key:'vehicles'|'peak'|'vision_ms') {return points.map((p,i)=>`${i===0||stamp(p,recorded)-stamp(points[i-1],recorded)>bucketSeconds*2?'M':'L'}${x(p).toFixed(2)},${y(Number(p[key])).toFixed(2)}`).join(' ');}
 return <article className="analysis-chart"><div className="chart-heading"><h3>{title}</h3><span>{unit}</span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${title}. ${points.length} observed time intervals. Use the time inspector below for values.`}>
 {[0,.5,1].map(f=><g key={f}><line x1={left} y1={y(max*f)} x2={width-right} y2={y(max*f)} className="chart-grid"/><text x={left-8} y={y(max*f)+4} textAnchor="end">{n(max*f)}</text></g>)}
 {metric==='vehicles'&&<path d={path('peak')} className="chart-peak"/>}<path d={path(metric)} className="chart-line"/>
 <line x1={x(points[index])} y1={top} x2={x(points[index])} y2={height-bottom} className="chart-cursor"/>
 {points.map((p,i)=><circle key={i} cx={x(p)} cy={y(Number(p[metric]))} r={i===index?5:3} className="chart-dot" onClick={()=>onSelect(i)}><title>{time(p,recorded)} · {n(Number(p[metric]))} {unit} · {p.samples} analyzed frames</title></circle>)}
 <text x={left} y={height-5}>{time(points[0],recorded)}</text><text textAnchor="end" x={width-right} y={height-5}>{time(points.at(-1)!,recorded)}</text></svg>
 {metric==='vehicles'&&<div className="chart-key"><span><i/>Average vehicles per frame</span><span><i className="peak-key"/>Peak in interval</span></div>}
 </article>;
}

export default function SourceAnalytics({source,jobs,onReview,onPlayback,loadingPlayback}:{source:Source;jobs:Job[];onReview:(i:Incident)=>void;onPlayback:(id:string,seconds:number)=>void;loadingPlayback:boolean}){
 const query=useQueryClient();const [recording,setRecording]=useState('');const [minutes,setMinutes]=useState(60);const [inspected,setInspected]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();
 const recorded=source.kind==='upload';
 const recordings=useInfiniteQuery({queryKey:['source-recordings',source.id],initialPageParam:0,queryFn:({pageParam})=>api<Job[]>(`/jobs?source_id=${source.id}&offset=${pageParam}`),getNextPageParam:(last,pages)=>last.length===100?pages.length*100:undefined,enabled:recorded,refetchInterval:5000});
 const available=recordings.data?.pages.flat()||jobs.filter(j=>j.source_id===source.id);const jobId=recording||available[0]?.id;
 const result=useQuery({queryKey:['source-analytics',source.id,jobId||'',minutes],queryFn:()=>api<Analytics>(`/sources/${source.id}/analytics?window_minutes=${minutes}${recorded&&jobId?'&job_id='+jobId:''}`),refetchInterval:5000});
 const data=result.data;const points=data?.points||[];const index=Math.min(inspected??points.length-1,points.length-1);const point=points[index];
 const selectedJob=available.find(j=>j.id===jobId);const processing=selectedJob&&['queued','processing'].includes(selectedJob.status);
 async function build(){setBusy(true);setError(undefined);try{await api(`/jobs/${jobId}/analytics/start`,{method:'POST'});await query.invalidateQueries({queryKey:['jobs']});await result.refetch();}catch(e){setError(e);}finally{setBusy(false);}}
 function download(){if(!data)return;const rows=[['interval_start','interval_end','video_start_seconds','video_end_seconds','analyzed_frames','average_vehicles_per_frame','peak_vehicles_per_frame','average_vision_ms'],...points.map(p=>[p.at,p.end_at,p.video_seconds??'',p.video_end_seconds??'',p.samples,p.vehicles,p.peak,p.vision_ms])];const blob=new Blob([rows.map(row=>row.join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`analysis-${source.id}-${data.job_id||'live'}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="source-analytics" id="analysis-history"><div className="analytics-heading"><div><span className="eyebrow">SOURCE / ANALYSIS HISTORY</span><h2><BarChart3 size={26}/>The story in your footage</h2><p>{recorded?'Measurements tied to this recording’s playback time.':'Measurements from frames actually received by this feed.'}</p></div><div className="analytics-controls">{recorded?<label>Recording<select value={recording} onChange={e=>{setRecording(e.target.value);setInspected(null);}}><option value="">Latest recording</option>{available.map(j=><option key={j.id} value={j.id}>{j.original_name} · {new Date(j.created_at).toLocaleString()}</option>)}</select></label>:<label>Live history<select value={minutes} onChange={e=>{setMinutes(Number(e.target.value));setInspected(null);}}><option value={15}>Last 15 minutes</option><option value={60}>Last hour</option><option value={1440}>Last 24 hours</option></select></label>}{recordings.hasNextPage&&<button className="button outline small" disabled={recordings.isFetchingNextPage} onClick={()=>recordings.fetchNextPage()}>Load older recordings</button>}{!!points.length&&<button className="button outline small" onClick={download}><Download size={15}/>Export CSV</button>}</div></div>
 <ErrorMessage error={error||result.error||recordings.error}/>{result.isPending?<div className="quiet-panel"><Spinner/>Loading analysis history</div>:!points.length?<div className="analytics-empty"><BarChart3 size={35}/><h3>{processing?'Building your analysis timeline':'No measured frames in this history yet'}</h3><p>{recorded?(processing?'The graphs populate as the original recording is analyzed.':selectedJob?.status==='completed'?'This recording was analyzed before graph history was introduced. Build its graphs by analyzing the saved original again.':'Start or retry the recording analysis to collect measurements.'):'Start this camera or stream to see vehicle and processing trends. Live history keeps the last 24 hours.'}</p>{source.can_manage&&recorded&&selectedJob?.status==='completed'&&<button className="button lime" disabled={busy} onClick={build}>{busy?<Spinner/>:<Play size={16}/>}Build graphs from saved recording</button>}</div>:<>
 <div className="analytics-stats">{[{icon:Activity,value:n(data!.summary.samples),label:'Frames analyzed'},{icon:BarChart3,value:n(data!.summary.peak),label:'Peak vehicles in a frame'},{icon:Clock,value:n(data!.summary.average_vision_ms)+' ms',label:'Average vision processing'},{icon:ShieldCheck,value:(data!.events_truncated?'500+':String(data!.events.length)),label:'Incident candidates in history'}].map(s=><div key={s.label}><s.icon size={19}/><strong>{s.value}</strong><span>{s.label}</span></div>)}</div>
 <div className="analytics-chart-grid"><Trend points={points} recorded={recorded} bucketSeconds={data!.bucket_seconds} metric="vehicles" title="Vehicle presence" unit="vehicles / frame" onSelect={setInspected} index={index}/><Trend points={points} recorded={recorded} bucketSeconds={data!.bucket_seconds} metric="vision_ms" title="Vision processing time" unit="milliseconds" onSelect={setInspected} index={index}/></div>
 <div className="time-inspector"><label htmlFor={'analysis-time-'+source.id}>Inspect analysis time <strong>{time(point,recorded)}</strong></label><input id={'analysis-time-'+source.id} type="range" min={0} max={points.length-1} value={index} step={1} onChange={e=>setInspected(Number(e.target.value))} aria-valuetext={`${time(point,recorded)}, ${point.samples} frames, average ${point.vehicles} vehicles, peak ${point.peak}, ${point.vision_ms} milliseconds`}/><div aria-live="polite"><span><strong>{n(Number(point.vehicles))}</strong> avg vehicles</span><span><strong>{n(point.peak)}</strong> peak vehicles</span><span><strong>{n(point.samples)}</strong> frames sampled</span><span><strong>{n(Number(point.vision_ms))} ms</strong> vision processing</span></div></div>
 <div className="analytics-chart-grid"><article className="analysis-chart"><div className="chart-heading"><h3>Vehicle types observed</h3><span>Across analyzed frames</span></div><div className="vehicle-mix">{[['Cars',data!.summary.cars],['Motorcycles',data!.summary.motorcycles],['Buses',data!.summary.buses],['Trucks',data!.summary.trucks]].map(([label,count])=>{const total=data!.summary.cars+data!.summary.motorcycles+data!.summary.buses+data!.summary.trucks;const percent=total?Number(count)/total*100:0;return <div key={label}><span>{label}</span><div className="mix-bar"><i style={{width:percent+'%'}}/></div><strong>{n(Number(count))}</strong><small>{n(percent)}%</small></div>;})}</div><p className="chart-note">A tracked vehicle contributes once per analyzed frame. These are observations, not unique vehicles or traffic throughput.</p></article>
 <article className="analysis-chart"><div className="chart-heading"><h3>Incident timeline</h3><span>Click to review evidence</span></div>{data!.events.length?<div className="analysis-events">{[...data!.events].sort((a,b)=>(a.video_seconds??Date.parse(a.detected_at))-(b.video_seconds??Date.parse(b.detected_at))).map(event=><button key={event.id} onClick={()=>onReview(event)}><span className="event-time">{recorded?elapsed(event.video_seconds||0):new Date(event.detected_at).toLocaleTimeString()}</span><i/><div><Status value={event.status}/><small>{event.signals.supporting_frames} supporting frames · motion score {n(event.score)}</small></div><span>↗</span></button>)}</div>:<div className="timeline-clear"><ShieldCheck size={30}/><p>No incident candidates in this analysis history.</p></div>}{data!.events_truncated&&<p className="chart-note">Showing the latest 500 candidates.</p>}</article></div>
 {recorded&&data!.job_id&&<button className="button outline small" disabled={loadingPlayback} onClick={()=>onPlayback(data!.job_id!,point.video_seconds||0)}>{loadingPlayback?<Spinner/>:<Play size={15}/>}Open original at {time(point,true)}</button>}
 <p className="analytics-footnote">{recorded?`Recording: ${data!.recording?.original_name}. `:'Live history retains 24 hours. '}{data!.bucket_seconds}-second intervals, weighted by analyzed frames. Vision timing excludes transfer and database time. Gaps represent periods without analyzed frames.</p>
 </>}{!!points.length&&<SourceFeedback sourceId={source.id}/>}</section>;
}

function SourceFeedback({sourceId}:{sourceId:string}){
 const {user}=useAuth();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);const [error,setError]=useState<unknown>();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{await api(`/sources/${sourceId}/feedback`,{method:'POST',body:JSON.stringify({display_name:form.get('display_name'),rating:Number(form.get('rating')),quote:form.get('quote'),publish_consent:form.get('publish_consent')==='on'})});setSent(true);setOpen(false);}catch(e){setError(e);}finally{setBusy(false);}}
 return <div className="source-feedback"><div><MessageSquare size={21}/><div><h3>{sent?'Thanks for sharing your experience':'How did this analysis work for you?'}</h3><p>{sent?'Your feedback is saved. Public feedback is reviewed before appearing on the website.':'Share feedback based on the footage you just analyzed.'}</p></div>{!sent&&<button className="button outline small" onClick={()=>setOpen(!open)}>{open?'Close':'Share feedback'}</button>}</div>{open&&<form onSubmit={submit}><ErrorMessage error={error}/><div className="feedback-fields"><label>Display name<input name="display_name" defaultValue={user?.role==='visitor'?'':user?.name} required minLength={2} maxLength={80} autoComplete="name"/></label><label>Your rating<select name="rating" defaultValue="5">{[5,4,3,2,1].map(i=><option key={i} value={i}>{i} / 5</option>)}</select></label></div><label>Your experience<textarea name="quote" required minLength={20} maxLength={1000} rows={3} placeholder="What worked well, and what could be better?"/></label><label className="feedback-consent"><input type="checkbox" name="publish_consent"/>Allow this name, rating, and feedback to appear on the public website after review.</label><button className="button lime" disabled={busy}>{busy?<Spinner/>:<Star size={16}/>}Send feedback</button></form>}</div>;
}
