import {useEffect,useRef,useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {Camera,Square} from 'lucide-react';
import {api,raw} from './api';
import {EvidenceImage,ErrorMessage,Modal,Spinner} from './ui';
import type {Source} from './types';
export default function Webcam({source,onClose}:{source:Source;onClose:()=>void}){
 const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const active=useRef(false);const controller=useRef<AbortController|null>(null);const [running,setRunning]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();const [frames,setFrames]=useState(0);const [metrics,setMetrics]=useState<{tracks:unknown[];processing_fps:number}|null>(null);const query=useQueryClient();
 function cleanup(){active.current=false;controller.current?.abort();stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;}
 useEffect(()=>()=>{cleanup();api('/sources/'+source.id+'/stop',{method:'POST'}).catch(()=>{});},[source.id]);
 async function stop(){cleanup();setRunning(false);await api('/sources/'+source.id+'/stop',{method:'POST'}).catch(setError);query.invalidateQueries({queryKey:['sources']});}
 async function start(){setBusy(true);setError(undefined);try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access requires HTTPS or localhost.');stream.current=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:960},height:{ideal:540}},audio:false});if(video.current){video.current.srcObject=stream.current;await video.current.play();}await api('/sources/'+source.id+'/start',{method:'POST'});controller.current=new AbortController();active.current=true;setRunning(true);query.invalidateQueries({queryKey:['sources']});capture();}catch(e){cleanup();setError(e);}finally{setBusy(false);}}
 async function capture(){const canvas=document.createElement('canvas');const context=canvas.getContext('2d')!;while(active.current){try{const element=video.current;if(!element||!element.videoWidth)break;canvas.width=element.videoWidth;canvas.height=element.videoHeight;context.drawImage(element,0,0);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));if(!active.current)break;if(blob){const form=new FormData();form.append('file',blob,'frame.jpg');const response=await raw('/sources/'+source.id+'/frame',{method:'POST',body:form,signal:controller.current?.signal});const data=await response.json();if(active.current){setMetrics(data);setFrames(n=>n+1);}}await new Promise(resolve=>setTimeout(resolve,400));}catch(e){if(active.current){setError(e);await stop();}break;}}}
 return <Modal title={source.name+' · Webcam'} onClose={onClose} wide><p className="muted">Your browser sends camera frames while this window is open. Processing speed depends on server capacity.</p><ErrorMessage error={error}/><div className="camera-grid"><div><span className="eyebrow">CAMERA INPUT</span><video ref={video} autoPlay playsInline muted className="camera-video"/></div><div><span className="eyebrow">VEHICLE TRACKING</span>{frames>0?<EvidenceImage path={'/sources/'+source.id+'/snapshot'} version={String(frames)} alt="Latest camera frame with actual vehicle detections"/>:<div className="camera-placeholder"><Camera size={35}/><span>Processed frames will appear here</span></div>}</div></div><div className="camera-footer"><span className="muted">{frames} frames processed {metrics?`· ${metrics.tracks.length} tracked vehicles · ${metrics.processing_fps} processing fps`:''}</span>{running?<button className="button danger" onClick={stop}><Square size={16}/>Stop monitoring</button>:<button className="button lime" onClick={start} disabled={busy}>{busy?<Spinner/>:<Camera size={18}/>}Enable camera</button>}</div></Modal>;
}
